IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DuelSys_Web.Pages
{
    public class ErrorModel : PageModel
    {
        

        public void OnGet()
        {
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    public class IndexModel : PageModel
    {
        

        public void OnGet()
        {

        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/LoginPage.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LogicLayer;
using LogicLayer.CustomExceptions;
using LogicLayer.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace DuelSys_Web.Pages
{
    public class LoginPageModel : PageModel
    {
        [BindProperty]
        public Login login { get; set; }

        private readonly INotyfService _notyfService;
        private LoginAdmin _LoginAdmin;
        private UserAdmin _UserAdmin;

        public LoginPageModel(LoginAdmin loginAdmin, INotyfService notyfService, UserAdmin userAdmin)
        {
            _LoginAdmin = loginAdmin;
            _notyfService = notyfService;
            _UserAdmin = userAdmin;
        }
        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(_LoginAdmin.ValidateLogin(login))
                    {
                        User user = _UserAdmin.GetUserByEmail(login.Email);
                        List<Claim> claims = new List<Claim>();
                        claims.Add(new Claim(ClaimTypes.Role, user.Role.ToString()));
                        claims.Add(new Claim(ClaimTypes.Name, login.Email));

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));

                        _notyfService.Success("Succesfully logged in");
                        return RedirectToPage("Index");
                    }
                    else { return Page(); }
                }
                else
                {
                    throw new InvalidLoginInputException("You forgot to fill something in");
                }
            }
            catch(InvalidLoginInputException ex)
            {
                _notyfService.Error(ex.Message);
                return Page();
            }
            catch(DatabaseFailedException ex)
            {
                _notyfService.Error(ex.Message);
                return Page();
            }
            catch (Exception)
            {
                return Page();
            }
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Logout.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    [Authorize]
    public class LogoutModel : PageModel
    {
        private readonly INotyfService _toastNotification;

        public LogoutModel(INotyfService notyfService)
        {
            _toastNotification = notyfService;
        }
        public async Task<IActionResult> OnPostAsync()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);
            _toastNotification.Success("Succesfully logged out");
            return RedirectToPage("Index");
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Register.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LogicLayer;
using LogicLayer.CustomExceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public User user { get; set; }

        private readonly INotyfService notyfService;
        private UserAdmin _UserAdmin;

        public RegisterModel(INotyfService notyf, UserAdmin userAdmin)
        {
            this._UserAdmin = userAdmin;
            this.notyfService = notyf;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _UserAdmin.AddUser(new User(user.FirstName, user.LastName, user.Email, user.Password, 1));
                    this.notyfService.Success($"Succesfully Registered: {user.FirstName}");
                    return RedirectToPage("LoginPage");
                }
                else
                {
                    throw new InvalidUserInputException("You forgot to fill in certain boxes");
                }
            }
            catch (InvalidUserInputException ex)
            {
                this.notyfService.Error(ex.Message);
                return Page();
            }
            catch (DatabaseFailedException ex)
            {
                this.notyfService.Error(ex.Message);
                return Page();
            }
            catch (Exception)
            {
                this.notyfService.Error("This should not happen");
                return Page();
            }
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/TournamentInformation.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LogicLayer;
using LogicLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    public class TournamentInformationModel : PageModel
    {
        [BindProperty]
        public Tournament tournament { get; set; }
        public List<Sport> sports { get; set; }
        public List<TournamentSystem> tournamentSystems { get; set; }
        public List<TournamentMatch> tournamentUnRegisteredMatches { get; set; } = new();
        public List<TournamentMatch> tournamentRegisteredMatches { get; set; } = new();
        public List<Leaderboard> Leaderboard { get; set; }

        private TournamentAdmin _TournamentAdmin;
        private readonly INotyfService _notyfService;
        private SportAdmin _SportAdmin;

        public TournamentInformationModel(TournamentAdmin tournamentAdmin,SportAdmin sportAdmin, INotyfService notyfService)
        {
            _TournamentAdmin = tournamentAdmin;
            _notyfService = notyfService;
            _SportAdmin = sportAdmin;
        }

        public void OnGet(string id)
        {
            try
            {
                int tournamentId = Convert.ToInt32(id);
                this.tournament = _TournamentAdmin.GetTournamentWithParticipantsAndMatches(tournamentId);
                this.sports = _SportAdmin.GetAllSports();
                this.tournamentSystems = _TournamentAdmin.GetAllTournamentSystems();
                ViewData[tournament.Id.ToString()] = tournament.Users.Count;
                this.Leaderboard = _TournamentAdmin.MakeLeaderboard(tournamentId);
                ViewData["Na"] = "N/A";
                foreach(var match in this.tournament.TournamentMatches)
                {
                    if(match.Result == null)
                    {
                        this.tournamentUnRegisteredMatches.Add(match);

                        var userhome = tournament.Users.Single(x => x.Id == match.PlayerHomeId);
                        ViewData[$"{match.PlayerHomeId}player"] = $"{userhome.FirstName} {userhome.LastName}";

                        var userAway = tournament.Users.Single(x => x.Id == match.PlayerAwayId);
                        ViewData[$"{match.PlayerAwayId}player"] = $"{userAway.FirstName} {userAway.LastName}";
                    }
                }

                foreach(var match in this.tournament.TournamentMatches)
                {
                    if(match.Result != null)
                    {
                        this.tournamentRegisteredMatches.Add(match);

                        var userhome = tournament.Users.Single(x => x.Id == match.PlayerHomeId);
                        ViewData[$"{match.PlayerHomeId}player"] = $"{userhome.FirstName} {userhome.LastName}";

                        var userAway = tournament.Users.Single(x => x.Id == match.PlayerAwayId);
                        ViewData[$"{match.PlayerAwayId}player"] = $"{userAway.FirstName} {userAway.LastName}";
                       
                        ViewData[$"{match.Result.PlayerHomeScore}score"] = match.Result.PlayerHomeScore.ToString();
                        ViewData[$"{match.Result.PlayerAwayScore}score"] = match.Result.PlayerAwayScore.ToString();

                    }
                }
                
                //the place of the leaderboard
                int n = 1;
                foreach(var user in Leaderboard)
                {
                    ViewData[user.User.Id.ToString()] =  n++.ToString();
                    ViewData[user.User.FirstName] = user.User.FirstName;
                    ViewData[user.User.LastName] = user.User.LastName;
                    ViewData[user.Wincounter.ToString()] = user.Wincounter.ToString();
                }
            }
            catch (Exception ex)
            {
                _notyfService.Error(ex.Message);
            }
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/ViewTournaments.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using LogicLayer;
using LogicLayer.CustomExceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DuelSys_Web.Pages
{
    public class ViewTournamentsModel : PageModel
    {
        [BindProperty]
        public List<Tournament> tournaments { get; set; }
        public List<Sport> sports { get; set; }
        public List<TournamentSystem> tournamentSystems { get; set; }
        public User user { get; set; }

        private TournamentAdmin _TournamentAdmin;
        private UserAdmin _UserAdmin;
        private readonly INotyfService _notyfService;
        private SportAdmin _SportAdmin;

        public ViewTournamentsModel(TournamentAdmin tournamentAdmin,UserAdmin user, SportAdmin sportAdmin, INotyfService notyfService)
        {
            _TournamentAdmin = tournamentAdmin;
            _UserAdmin = user; 
            _notyfService = notyfService;
            _SportAdmin = sportAdmin;
        }
        public IActionResult OnGet()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    this.user = _UserAdmin.GetUserByEmail(User.Identity.Name);
                }
                this.tournaments = _TournamentAdmin.GetAllTournamentsWithUsers();
                this.sports = _SportAdmin.GetAllSports();
                this.tournamentSystems = _TournamentAdmin.GetAllTournamentSystems();
                foreach (var tournament in tournaments)
                {
                    ViewData[$"{tournament.Id}ID"] = tournament.Users.Count;

                    if (User.Identity.IsAuthenticated)
                    {
                        if (!_TournamentAdmin.CheckRegisteredForTournament(tournament.Id, user.Id))
                        {
                            ViewData[tournament.Id.ToString()] = "true";
                        }
                    }
                }
                return Page();
            }
            catch (DatabaseFailedException ex)
            {
                this._notyfService.Error(ex.Message);
                return RedirectToPage("Error");
            }
            catch(InvalidRegistrationTournamentInput ex)
            {
                this._notyfService.Error(ex.Message);
                return RedirectToPage("Error");
            }
            catch (Exception ex)
            {
                this._notyfService.Error(ex.Message);
                return Page();
            }
        }

        public IActionResult OnPostJoin(string id)
        {
            try
            {
                int tournamentid = Convert.ToInt32(id);
                User u = _UserAdmin.GetUserByEmail(User.Identity.Name);
                if (_TournamentAdmin.RegisterForTournament(u.Id, tournamentid))
                {
                    this._notyfService.Success("Succesfully signed-up!!!");
                    return RedirectToPage("ViewTournaments");
                }
                else
                {
                    return RedirectToPage("ViewTournaments");
                }
            }
            catch(InvalidRegistrationTournamentInput ex)
            {
                this._notyfService.Warning(ex.Message);
                return RedirectToPage("ViewTournaments");
            }
            catch (Exception ex)
            {
                this._notyfService.Error(ex.Message);
                return RedirectToPage("ViewTournaments");

            }
        }

        public IActionResult OnPostView(string id)
        {
            return RedirectToPage("TournamentInformation", new { id });
        }
    }
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}

<body>

	<div class="FlexboxHome">
		<div class="FlexboxHomeContent">
			<p>
				<h1>
					View and join tournaments
				</h1>
				<h3>Supported by DuelSys</h3>
			</p>
		</div>
	</div>

	
</body>

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/LoginPage.cshtml
@page
@model DuelSys_Web.Pages.LoginPageModel
@{
}
<body>
    <div class="flexboxLogin">
        <div class="InformationFlexBox">
            <div class="FLexBoxLogin-image FLexBoxLogin-image1"></div>
            <form method="post">
                <input type = "text" asp-for="login.Email" placeholder="Email" /><br />
                <input type="password" asp-for="login.Password" placeholder="Password" /><br /><br />
               
                    <button class="button1" type="submit"
                            value = "button">Sign in
                    </button>
                   
                    <button class="button1" type="button" value="Some text" onclick="window.location.href='@Url.Content("Register")';"><span></span>Register</button>

                
            </form>
        </div>
    </div>
    	


</body>

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Logout.cshtml
@page
@model DuelSys_Web.Pages.LogoutModel
@{
}

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/Register.cshtml
@page
@model DuelSys_Web.Pages.RegisterModel
@{
}

<body>
	<div class="flexboxRegister">
		<div class = "flexboxRegisterContent">
			 <h1>Create Account</h1>
			<div class="FLexBoxLogin-image FLexBoxLogin-image2"></div>
			<form method="post">
				<input type="text" asp-for="user.FirstName" placeholder="First name" /><br /><br />
				<input type="text" asp-for="user.LastName" placeholder="Last name" /><br /><br />
				<input type="text" asp-for="user.Email" placeholder="Email" /><br /><br />
				<input type="password" asp-for="user.Password" placeholder="Password" /><br /><br />

				<button class="button1" type="submit"
                            value = "button">Create account
                    </button>
                   
                    <button class="button1" type="button" value="Some text" onclick="window.location.href='@Url.Content("LoginPage")';"><span></span>Log in</button>

			</form>
		</div>
	</div>
</body>

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/TournamentInformation.cshtml
@page "{id}"
@using LogicLayer.Models
@model DuelSys_Web.Pages.TournamentInformationModel
@{
}

<body>
	<br /><br />
	<div class="flexboxHeading">
		<div class="flexboxHeadingContent">
			<div class="sizeText">
				Tournament Information
			</div>
		</div>
	</div>
	<div class="tablefix">
		<table class="table table-striped table-dark">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Id</th>
					<th scope="col">description</th>
					<th scope="col">start date</th>
					<th scope="col">end date</th>
					<th scope="col">location</th>
					<th scope="col">minimum players</th>
					<th scope="col">maximum players</th>
					<th scope="col">sport</th>
					<th scope="col">tournament type</th>
					<th scope="col">Amount signed-up</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th scope="col">@Model.tournament.Id</th>
					<th scope="col">@Model.tournament.Description</th>
					<th scope="col">@Model.tournament.StartDate.Date.ToString()</th>
					<th scope="col">@Model.tournament.EndDate.Date</th>
					<th scope="col">@Model.tournament.Location</th>
					<th scope="col">@Model.tournament.MinimumPlayers</th>
					<th scope="col">@Model.tournament.MaximumPlayers</th>
					<th scope="col">@Model.sports[Model.tournament.SportId].Name</th>
					<th scope="col">@Model.tournamentSystems[Model.tournament.TournamentTypeId].Name</th>
					<th scope="col">@Model.ViewData[Model.tournament.Id.ToString()]</th>
			</tbody>
		</table>
	</div>
	<div class="flexboxHeading">
		<div class="flexboxHeadingContent">
			<div class="sizeText">
				Not played matches
			</div>
		</div>
	</div>
	<div class="tablefix">
		<table class="table table-striped table-dark">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Match Id</th>
					<th scope="col">Player Home</th>
					<th scope="col">Player Away</th>
					<th scope="col">Score Home</th>
					<th scope="col">Score Away</th>
				</tr>
				

			</thead>

			<tbody>
				
					@foreach(var match in Model.tournamentUnRegisteredMatches)
					{
						<tr>
						<th scope="col">@match.Id</th>
						<th scope="col">@Model.ViewData[$"{match.PlayerHomeId}player"]</th>
						<th scope="col">@Model.ViewData[$"{match.PlayerAwayId}player"]</th>
						<th scope="col">@ViewData["Na"]</th>
						<th scope="col">@ViewData["Na"]</th>
						</tr>
					}

					
			</tbody>
		</table>


	</div>

	<div class="flexboxHeading">
		<div class="flexboxHeadingContent">
			<div class="sizeText">
				Played matches
			</div>
		</div>
	</div>

	<div class="tablefix">
		<table class="table table-striped table-dark">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Match Id</th>
					<th scope="col">Player Home</th>
					<th scope="col">Player Away</th>
					<th scope="col">Score Home</th>
					<th scope="col">Score Away</th>
				</tr>
				

			</thead>

			<tbody>
				
					@foreach(var match in Model.tournamentRegisteredMatches)
					{
						<tr>
							<th scope="col">@match.Id</th>
							<th scope="col">@Model.ViewData[$"{match.PlayerHomeId}player"]</th>
							<th scope="col">@Model.ViewData[$"{match.PlayerAwayId}player"]</th>
							<th scope="col">@Model.ViewData[$"{match.Result.PlayerHomeScore}score"]</th>
							<th scope="col">@Model.ViewData[$"{match.Result.PlayerAwayScore}score"]</th>
						</tr>
					}
				
				
				
			</tbody>
		</table>


	</div>

	<div class="flexboxHeading">
		<div class="flexboxHeadingContent">
			<div class="sizeText">
				Ranking
			</div>
		</div>
	</div>

	<div class="tablefix">
		<table class="table table-striped table-dark">
			<thead class="thead-dark">
				<tr>
					<th scope="col">Place</th>
					<th scope="col">Firstname</th>
					<th scope="col">Lastname</th>
					<th scope="col">WinCounter</th>
				</tr>
				

			</thead>

			<tbody>
				@foreach(var user in Model.Leaderboard)
				{
					<tr>
						<th scope="col">@Model.ViewData[user.User.Id.ToString()]</th>
						<th scope="col">@Model.ViewData[user.User.FirstName]</th>
						<th scope="col">@Model.ViewData[user.User.LastName]</th>
						<th scope="col">@Model.ViewData[user.Wincounter.ToString()]</th>

					</tr>
				}
			</tbody>
		</table>


	</div>


</body>

IndividualProjects/s2-cb-07-synthesis-assignment/DuelSys/DuelSys-Web/Pages/ViewTournaments.cshtml
@page
@model DuelSys_Web.Pages.ViewTournamentsModel
@{
}

<body>
	<br /><br />
	<div class="flexboxHeading">
		<div class="flexboxHeadingContent">
			<div class="sizeText">
				View/Sign-up for tournaments
			</div>
		</div>
	</div>
	<div class="tablefix">
	<table class="table table-striped table-dark">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Id</th>
				<th scope="col">description</th>
				<th scope="col">start date</th>
				<th scope="col">end date</th>
				<th scope="col">location</th>
				<th scope="col">minimum players</th>
				<th scope="col">maximum players</th>
				<th scope="col">sport</th>
				<th scope="col">tournament type</th>
				<th scope="col">Amount signed-up</th>
				<th scope="col">View information</th>
				<th scope="col">Sign-up</th>
			</tr>
		</thead>
		<tbody>
		
			@foreach (var tournament in Model.tournaments)
			{
				<tr>
					<th scope="col">@tournament.Id</th>
					<th scope="col">@tournament.Description</th>
					<th scope="col">@tournament.StartDate.Date.ToString()</th>
					<th scope="col">@tournament.EndDate.Date</th>
					<th scope="col">@tournament.Location</th>
					<th scope="col">@tournament.MinimumPlayers</th>
					<th scope="col">@tournament.MaximumPlayers</th>
					<th scope="col">@Model.sports[tournament.SportId].Name</th>
					<th scope="col">@Model.tournamentSystems[tournament.TournamentTypeId].Name</th>
					<th scope="col">@Model.ViewData[$"{tournament.Id}ID"]</th>
					<form method="post" asp-route-id="@tournament.Id">
						<th scope="col"><button class="button1" type = "submit" value="submit" id="@tournament.Id" asp-route-id="@tournament.Id" asp-page-handler="View">View Tournament</button> </th>
					</form>
					@if(@User.Identity.IsAuthenticated)
					{
						@if(ViewData[tournament.Id.ToString()] == "true")
						{
							<form method="post"  asp-route-id="@tournament.Id">
								<th scope="col"><button class="button1" type="submit" value ="submit" onclick="return confirm('Are you sure you want to join this tournamment?')" id="@tournament.Id" asp-route-id="@tournament.Id" asp-page-handler="Join" > JOIN </button></th>
							</form>
						}
						else
						{
							<th scope = "col"> Signed in</th>
						}
					}
					else
					{
						<th scope="col"><a class="nav-link" asp-page="/LoginPage">Login</a> </th>
					}
				</tr>
			}
		</tbody>
	</table>
	</div>
	
	
</body>