GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/AbsencePage.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Group_Project_Website;
using MediaBazaarWeb.DataLayer;
using MediaBazaarWeb.LogicLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWeb.Pages
{
    [Authorize]
    public class AbsencePageModel : PageModel
    {
        [BindProperty]
        public Absence absence{ get; set; }
        [BindProperty]
        public Employee employee { get; set; }
        private readonly INotyfService Notyf;

        [BindProperty]
        public Vacation vacation { get; set; }

        public AbsencePageModel(INotyfService notyfService)
        {
            this.Notyf = notyfService;
        }
        public void OnGet()
        {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            this.employee = employeeManagement.GetEmployeeByEmail(User.Identity.Name);
            ViewData["Name"] = $"{employee.FirstName} {employee.LastName}";
            ViewData["Id"] = employeeManagement.GetEmployeeByEmail(User.Identity.Name).ID;
            
        }

        public IActionResult OnPostAbsence()
        {
            AbsenceManagement absenceManagement = new AbsenceManagement();
            EmployeeManagement employeeManagement = new EmployeeManagement();
            VacationLogic vacationLogic = new VacationLogic();
            int id = employeeManagement.GetEmployeeByEmail(User.Identity.Name).ID;
            if(absenceManagement.CheckAbsenceExist(id, absence))
            {
                this.Notyf.Information($"You already said you can not come to work on this date, {absence.Date.ToString("yyyy/MM/dd")} .");
                return RedirectToAction("AbsencePage");
            }
            else
            {
                if (vacationLogic.CheckValAddAbsence(absence))
                {
                    if (absenceManagement.AddAbsence(id, absence))
                    {
                        this.Notyf.Success("succesfully send");
                        return RedirectToAction("AbsencePage");
                    }
                    else
                    {
                        this.Notyf.Error("nothing added");
                        return RedirectToAction("AbsencePage");

                    }
                }
                else
                {
                    this.Notyf.Error($"This date: {absence.Date.ToString("yyyy/MM/dd")} already went by");
                    return RedirectToAction("AbsencePage");
                }

            }




        }

        public IActionResult OnPostVacation()
        {
            AbsenceManagement absenceManagement = new AbsenceManagement();
            EmployeeManagement employeeManagement = new EmployeeManagement();
            VacationLogic vacationLogic = new VacationLogic();
            if (vacationLogic.CheckValAddVacation(vacation))
            {
                int id = employeeManagement.GetEmployeeByEmail(User.Identity.Name).ID;
                if (absenceManagement.AddVacation(id, vacation))
                {
                    this.Notyf.Success($"Succesfully send the request for {vacation.StartDate.ToString("yyyy-MM-dd")} until {vacation.EndDate.ToString("yyyy-MM-dd")}");

                }
                else
                {
                    this.Notyf.Error("Failed to add this request");
                }
            }
            else
            {
                this.Notyf.Error("Your input is wrong");
            }
            return RedirectToAction("AbsencePage");

        }
    }
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Index.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Group_Project_Website;
using Group_Project_Website.Logic;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace MediaBazaarWeb.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public LogInHandler logins { get; set; }
        private readonly INotyfService Notyf;
        public Employee employee { get; set; }

        public IndexModel(INotyfService toastNotificationService)
        {
            this.Notyf = toastNotificationService;
        }

        public void OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                EmployeeManagement employeeManagement = new EmployeeManagement();
                this.employee = employeeManagement.GetEmployeeByEmail(User.Identity.Name);
                ViewData["name"] = $"{employee.FirstName} {employee.LastName}";
            }
            

        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {

                UserHelper userHelper = new UserHelper();
                if (userHelper.IsValidEmail(logins.email))
                {
                    if (userHelper.ValidateLogin(logins.email, logins.password))
                    {
                        EmployeeManagement employeeManagement = new EmployeeManagement();
                        Employee loggedEmployee = employeeManagement.GetEmployeeByEmail(logins.email);

                        List<Claim> claims = new List<Claim>();
                        claims.Add(new Claim(ClaimTypes.Email, logins.email));
                        claims.Add(new Claim(ClaimTypes.Name, logins.email));
                        claims.Add(new Claim(ClaimTypes.Role, loggedEmployee.ID.ToString()));
                        claims.Add(new Claim("id", "1"));

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));
                        this.Notyf.Success($"Succesfully logged in");
                        return RedirectToPage("Schedule");
                    }
                    else
                    {
                        Notyf.Error("Password Incorrect");
                        return new RedirectToPageResult("index");
                    }
                }
                else
                {
                    Notyf.Error("Your email is incorrect");
                    return new RedirectToPageResult("index");
                }
            }
            else
            {
                Notyf.Error("something went wrong");
                return new RedirectToPageResult("index");
            }
        }
    }
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Logout.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWeb.Pages
{
    public class LogoutModel : PageModel
    {

        private readonly INotyfService Notyf;

        public LogoutModel(INotyfService notyfService)
        {
            Notyf = notyfService;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await HttpContext.SignOutAsync(
                CookieAuthenticationDefaults.AuthenticationScheme);
            this.Notyf.Success("succesfully logged out");
            return RedirectToPage("index");
        }
    }
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/PersonalInformation.cshtml.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Group_Project_Website;
using MediaBazaarWeb.DataLayer;
using MediaBazaarWeb.LogicLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWeb.Pages
{
    [Authorize]
    public class PersonalInformationModel : PageModel
    {
        [BindProperty]
        public Employee employee { get; set; }
        public Employee UpdatedEmployee { get; set; }
        [BindProperty]
        public ContactPerson ContactPerson { get; set; }

        private readonly INotyfService Notyf;

        public PersonalInformationModel(INotyfService notyfService)
        {
            this.Notyf = notyfService;
        }
        public IActionResult OnGet()
        {
            EmployeeManagement employeeManagement = new EmployeeManagement();
            employee = employeeManagement.GetEmployeeByEmail(User.Identity.Name);
            ContactPersonManagement contactPersonManagement = new ContactPersonManagement();
            this.ContactPerson = contactPersonManagement.GetContactPersonByEmployeeId(employee.ID);
            PersonalInformationManagement personalInformationManagement = new PersonalInformationManagement();
            if(personalInformationManagement.GetUpdatedInformationById(employee.ID) != null)
            {
                string PotentialUpdate = "Pending change: ";
                this.UpdatedEmployee = personalInformationManagement.GetUpdatedInformationById(employee.ID);
                if(UpdatedEmployee.Email != employee.Email){ViewData["Email"] = PotentialUpdate + UpdatedEmployee.Email;}
                if(UpdatedEmployee.Street != employee.Street){ViewData["Street"] = PotentialUpdate + UpdatedEmployee.Street;}
                if(UpdatedEmployee.HouseNumber != employee.HouseNumber){ViewData["HouseNumber"] = PotentialUpdate + UpdatedEmployee.HouseNumber;}
                if(UpdatedEmployee.City != employee.City){ViewData["City"] = PotentialUpdate + UpdatedEmployee.City;}
                if(UpdatedEmployee.PostalCode != employee.PostalCode){ViewData["PostalCode"] = PotentialUpdate + UpdatedEmployee.PostalCode;}
                if(UpdatedEmployee.Phonenumber != employee.Phonenumber){ViewData["PhoneNumber"] = PotentialUpdate + UpdatedEmployee.Phonenumber;}
                return Page();
            }
            return Page();
        }

        public IActionResult OnPostUpdate()
        {
            PersonalInformationLogic personalInformationLogic = new PersonalInformationLogic();
            if (personalInformationLogic.CheckValidationUpdate(employee.FirstName, employee.LastName, employee.Email, employee.Street, employee.City, employee.HouseNumber, employee.PostalCode, employee.Phonenumber))
            {
                PersonalInformationManagement personalInformationManagement = new PersonalInformationManagement();
                if (personalInformationManagement.CheckRequestUpdateExist(employee.ID))
                {
                    if (personalInformationManagement.UpdateRequestUpdateInformationEmp(employee))
                    {
                        if (personalInformationLogic.checkUpdatedValidation(employee.ID, employee.Email, User.Identity.Name))
                        {
                            this.Notyf.Information("Deleted changes because everything is the same", 6);
                            return RedirectToPage("PersonalInformation");

                        }
                        else
                        {
                            this.Notyf.Information("Updated your changes with succes");
                            return RedirectToPage("PersonalInformation");
                        }
                    }
                    else
                    {
                        return RedirectToPage("PersonalInformation");
                    }
                }
                else
                {
                    if(personalInformationLogic.CheckSameData(User.Identity.Name, employee.FirstName, employee.LastName, employee.Email, employee.Street, employee.City, employee.HouseNumber, employee.PostalCode, employee.Phonenumber))
                    {
                        this.Notyf.Information("You did not make any changes, update not possible");
                        return RedirectToPage("PersonalInformation");
                    }
                    else
                    {
                        if (personalInformationManagement.AddRequestUpdateInformationEmp(employee))
                        {
                            this.Notyf.Success("Succesfully send the changes", 5);
                            return RedirectToPage("PersonalInformation");
                        }
                        else
                        {
                            return RedirectToPage("PersonalInformation");
                        }
                    }
                   
                }
            }
            else
            {
                return RedirectToPage("PersonalInformation");
            }
        }

        public IActionResult OnPostContactUpdate()
        {
            PersonalInformationLogic personalInformationLogic = new PersonalInformationLogic();
            PersonalInformationManagement personalInformationManagement = new PersonalInformationManagement();
            if (personalInformationLogic.CheckValContactPerson(ContactPerson))
            {
                this.Notyf.Success("Updated with succes");
                personalInformationManagement.UpdateContactPerson(ContactPerson);
            }
            else
            {
                this.Notyf.Warning("Wrong input");
            }
            return RedirectToPage("PersonalInformation");

        }
    }
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Schedule.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;
using MediaBazaar.Data_Layer;
using System.Security.Claims;
using Group_Project_Website.Logic;
using System.Globalization;

namespace Group_Project_Website.Pages
{
    [Authorize]
    public class ScheduleModel : PageModel
    {
        [BindProperty]
        public scheduleHandler Handler { get; set; }
        public static string name { get; set; }
        public UserHelper Userhelper = new UserHelper();
        public EmployeeManagement EmployeeManagement = new EmployeeManagement();    
        public void OnGet()
        {
            Employee employee;
            this.Handler = new scheduleHandler();
            employee = EmployeeManagement.GetEmployeeByEmail(User.Identity.Name);
            name = employee.FirstName;
            Handler.AddAllShifts(employee.FirstName);
            CultureInfo ciCurr = CultureInfo.CurrentCulture;
            int weekNum = ciCurr.Calendar.GetWeekOfYear(DateTime.Now, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday);
            scheduleHandler.selectedweek = Convert.ToInt32(weekNum);
            scheduleHandler.selectedmonth = Convert.ToInt32(DateTime.Now.Month);
            scheduleHandler.selectedyear = Convert.ToInt32(DateTime.Now.Year);
        }

        public IActionResult OnPostNext()
        {
            Handler.nextWeek();
            return Page();
        }
        public IActionResult OnPostPrevious()
        {
           
            this.Handler.PreviousWeek();
            return Page();
        }

    }
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/AbsencePage.cshtml
@page
@model MediaBazaarWeb.Pages.AbsencePageModel
@{
}


<section class="flexboxAbsenceinfo">
	<div class="flexboxAbsenceContent">
		<div class="TextAbsence">
			<form method="post">
				<h1>One day absenced</h1>
				<input type="text" value="@ViewData["Name"]" readonly /><br />

				<input type="text" value="@ViewData["Id"]" readonly><br>

				<span asp-validation-for="absence.Date"></span>
				<input type="date" asp-for="absence.Date" placeholder="date" />

				<span asp-validation-for="absence.Reason"></span>
				<textarea id="description" asp-for="absence.Reason" placeholder="Reason" rows="5" cols="30"></textarea>

				<button type="submit" class="button" value="Absence" onclick="return confirm('Are you sure everything is correct?')" id="Absence" asp-page-handler="Absence"><span></span>Send</button>

			</form>
		</div>
	</div>
</section>

<section class="flexboxVacationinfo">
	<div class="flexboxVacationContent">
		<div class="TextAbsence">
			<form method="post">
				<h1>Vacation</h1>
				<input type="text" value="@ViewData["Name"]" readonly /><br />

				<h4>Start date</h4>
				<input type="date" asp-for="vacation.StartDate" placeholder="start date" />

				<h4>End date</h4>
				<input type="date" asp-for="vacation.EndDate" placeholder="end date" />

				<span asp-validation-for="absence.Reason"></span>
				<textarea id="description" asp-for="vacation.Reason" placeholder="Reason" rows="5" cols="30"></textarea>

				<button type="submit" class="button" value="Vacation" onclick="return confirm('Are you sure everything is correct?')" id="Vacation" asp-page-handler="Vacation"><span></span>Send</button>

			</form>
		</div>
	</div>
</section>


@section scripts{
<partial name="_ValidationScriptsPartial" />
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Index.cshtml
@page
@model MediaBazaarWeb.Pages.IndexModel
@{
    ViewData["Title"] = "Login page";
}

<div class="banner">
</div>
<div class="center">
    @if (!User.Identity.IsAuthenticated)
    {
         <h1>Login</h1>
    <form method="post">
        <div class="txt_field">
            <input asp-for="logins.email" type="text" required />
            <span asp-validation-for="logins.email"></span>
            <label>email</label>
        </div>
        <div class="txt_field">
            <input asp-for="logins.password" type="password" required />
            <span asp-validation-for="logins.password"></span>
            <label>Password</label>
        </div>
        <input type="submit" value="Login">
        </form>
    }
    else
    {
        <h1>Welcome</h1>
        <h2>@ViewData["name"]</h2>
    }

</div>

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Logout.cshtml
@page
@model MediaBazaarWeb.Pages.LogoutModel
@{
}

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/PersonalInformation.cshtml
@page
@model MediaBazaarWeb.Pages.PersonalInformationModel
@{
}

<body>


	<form method="post">

	<div class="flexboxPersonalInfo">
		<div class="flexboxPersonalInforContent">
			<div class="Title">
				<h1>Personal information</h1>
				<h4>Read only</h4>
				<div class="SizeText">

						<h5>First name</h5><input type="text" asp-for="employee.FirstName" readonly>
						<h5>Last name</h5><input type="text" asp-for="employee.LastName" readonly>
						<h5>ID</h5><input type="text" asp-for="employee.ID" readonly>

						<h5>Salary</h5><input type="text" asp-for="employee.Salary" readonly>

						<h5>FTE</h5><input type="text" asp-for="employee.FTE" readonly>
						<h5>BSN</h5><input type="text" asp-for="employee.Bsn" readonly>

				</div>
			</div>
		</div>


		<div class="flexboxPersonalInforContent">
			<div class="Title">
				<h1>Personal information</h1>
				<h4>Changeable</h4>
				<div class="SizeText">
					

						<h5>Email</h5><input type="text" asp-for="employee.Email"><br />
						<span>@ViewData["Email"]</span>

						<h5>Street</h5><input type="text" asp-for="employee.Street"><br />
						<span>@ViewData["Street"]</span>

						<h5>Housenumber</h5><input type="text" asp-for="employee.HouseNumber"><br />
						<span>@ViewData["HouseNumber"]</span>


						<h5>City</h5><input type="text" asp-for="employee.City"><br />
						<span>@ViewData["City"]</span>

						<h5>Postalcode</h5><input type="text" asp-for="employee.PostalCode"><br />
						<span>@ViewData["PostalCode"]</span>


						<h5>Phone</h5><input type="text" asp-for="phone"><br />
						<span>@ViewData["PhoneNumber"]</span>
						<br />
						<button class="button" type="submit" value="Update" onclick="return confirm('Are you sure you everything is filled in correctly?')" id="Update" asp-page-handler="Update">Request update information</button>
					
				</div>
			</div>
		</div>
	</div>
</form>




	<div class="flexboxSmallInfo">
		<div class="flexboxSmallInfoContent">
			<div class="SizeText">

				<div class="Title">
					<h1>Contact Information</h1>
					<form method="post">
						<h5>Name</h5><input type="text" asp-for="ContactPerson.Name" />
						<h5>Email</h5><input type="text" asp-for="ContactPerson.Email" />
						<h5>Phone</h5><input type="text" asp-for="ContactPerson.Phone" /> <br /><br />
						<button class="button" type="submit" onclick="return confirm('Are you sure you want to update your date?')" value="ContactUpdate" id="ContactUpdate" asp-page-handler="ContactUpdate">Update</button>
					</form>

				</div>
			</div>
		</div>


	</div>



</body>

GroupProjects/prj-cb07-group-2-media-bazar/Software/MediaBazaar/MediaBazaarWeb/Pages/Schedule.cshtml
@page
@model Group_Project_Website.Pages.ScheduleModel
@{
    
    <div class="navbar">
    <form method="post">
           <button class="button", asp-page-handler="Previous"  style="float:left;">Previous Week</button>
           <h1 style="float:left; padding: 0px 25px;">Week: @Logic.scheduleHandler.selectedweek</h1>
           <button class="button", asp-page-handler="Next" type="submit"  style="float:left;">Next Week</button>
    </form>
    </div>

    Logic.scheduleHandler handler = new Logic.scheduleHandler();
    string[] Tableheaders = new string[] {
            "",
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday"
    };
<background>
    <table>
        <thead>
            <tr>
                @{
                    foreach (var head in Tableheaders)
                    {
                        <th>
                            @head
                        </th>
                    }
                }
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Morning</td>
                @{ for (int i = 0; i <= 6; i++)
                    {
                        foreach (Logic.ScheduleInfo info in handler.getAllShifts(ScheduleModel.name))
                        {
                            if (i == Convert.ToInt32(info.weekday) && info.type == "1" && Logic.scheduleHandler.selectedweek == info.week &&Logic.scheduleHandler.selectedyear == Convert.ToInt32(info.year))
                            { <td style="background-color: #5dce92"></td> i++;
                            }
                        }
                     <td style="background-color: #b34b4b "></td>
                    }
                }
            </tr>
            <tr>
                <td>After Noon</td>
                @{ for (int i = 0; i <= 6; i++)
                    {
                        foreach (Logic.ScheduleInfo info in handler.getAllShifts(ScheduleModel.name))
                        {
                            if (i == Convert.ToInt32(info.weekday) && info.type == "2" && Logic.scheduleHandler.selectedweek == info.week && Logic.scheduleHandler.selectedyear == Convert.ToInt32(info.year))
                            {<td style="background-color: #5dce92"></td> i++; }
                        }
                        <td style="background-color: #b34b4b "></td>
                    }
                }
            </tr>
            <tr>
                <td>Evening</td>
                @{ for (int i = 0; i <= 6; i++)
                    {
                        foreach (Logic.ScheduleInfo info in handler.getAllShifts(ScheduleModel.name))
                        {
                            if (i == Convert.ToInt32(info.weekday) && info.type == "3" && Logic.scheduleHandler.selectedweek == info.week && Logic.scheduleHandler.selectedyear == Convert.ToInt32(info.year))
                            { <td style="background-color: #5dce92"></td> i++;}
                        }
                        <td style="background-color: #b34b4b"></td>
                    }
                }
            </tr>
        </tbody>
    </table>
    <h1 style="color: #5dce92">green = shift planned </h1>
    <h1 style="color: #b34b4b">red = no shift planned</h1>
</background>
}